# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qCwbesEYFO2ULsEZNeIbIUhw7cINLRAc
"""

import streamlit as st
import pickle as pkl
import numpy as np

# Load the trained model
model = pkl.load(open('RF_class.pkl', 'rb'))

# Streamlit app
def main():
    st.title('Iris Flower Prediction App')

    # User input for features
    sepal_length = st.slider('Sepal Length', 4.0, 8.0, 5.0)
    sepal_width = st.slider('Sepal Width', 2.0, 4.5, 3.0)
    petal_length = st.slider('Petal Length', 1.0, 7.0, 4.0)
    petal_width = st.slider('Petal Width', 0.1, 2.5, 1.3)

    if st.button('Predict'):
        features = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
        prediction = model.predict(features)
        class_names = ['Setosa', 'Versicolor', 'Virginica']
        st.success(f'Prediction: {class_names[prediction[0]]}')

if __name__ == '__main__':
    main()